language: node_js

node_js:
  - 9

notifications:
  email: false

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test

      before_script:
        - npm prune

      after_script:
        - npx codecov

    - stage: release
      if: branch = master
      script:
        - npx semantic-release
        - |
          mkdir npm-install-test
          cd npm-install-test
          npm init -y
          npm i @matzkoh/slack-outgoing-textlint
